apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuberdemo

spec:
  replicas: 1
  selector:
    matchLabels:
      app: kuberdemo
  template:
    metadata:
      labels:
        app: kuberdemo
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:kuberdemodeployment.yml
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - minikube
      containers:
        - name: kuberdemo
          image: solidwave/kuberdemo:#VERSION#
          ports:
            - containerPort: 8080
