name: ci

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
    
      - name: Tag and Push Docker Image
        run: |
         docker buildx build -t kuberDemo -f ./kuberDemo/Dockerfile .
         docker tag kuberdemo solidwave/kuberdemo:${{ github.run_number }}
         docker push solidwave/kuberdemo:${{ github.run_number }}
